server:
  port: 8000

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        # === USER SERVICE ===

        - id: user-service-access
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v1/api/access/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}

        - id: user-service-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v1/api/users/**, /user-service/v1/api/managers/**, /user-service/v1/api/shelters/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}
            - UserAuthorizationHeaderFilter

        ### <ACTUATOR> ###
        - id: user-service-actuator
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}

        # Swagger API Docs
        - id: user-service-swagger
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}

        # Swagger UI 정적 리소스
        - id: user-service-swagger-ui
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/swagger-ui.html
            - Path=/user-service/swagger-ui/**
            - Path=/user-service/webjars/**
            - Path=/user-service/swagger-resources/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}

        # === MANAGER SERVICE ===

        - id: manager-service-common
          uri: lb://MANAGER-SERVICE
          predicates:
            - Path=/manager-service/health_check, /manager-service/welcome
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/manager-service/(?<segment>.*), /${segment}

        - id: manager-service-access
          uri: lb://MANAGER-SERVICE
          predicates:
            - Path=/manager-service/v1/api/access/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/manager-service/(?<segment>.*), /${segment}

        - id: manager-service-api
          uri: lb://MANAGER-SERVICE
          predicates:
            - Path=/manager-service/v1/api/managers/**, /manager-service/v1/api/submissions/**, /manager-service/v1/api/super-authorities/**, /manager-service/v1/api/users/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/manager-service/(?<segment>.*), /${segment}
            - ManagerAuthorizationHeaderFilter

        - id: manager-service-actuator
          uri: lb://MANAGER-SERVICE
          predicates:
            - Path=/manager-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/manager-service/(?<segment>.*), /${segment}

        - id: manager-service-swagger
          uri: lb://MANAGER-SERVICE
          predicates:
            - Path=/manager-service/v3/api-docs/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/manager-service/(?<segment>.*), /${segment}

        - id: manager-service-swagger-ui
          uri: lb://MANAGER-SERVICE
          predicates:
            - Path=/manager-service/swagger-ui.html
            - Path=/manager-service/swagger-ui/**
            - Path=/manager-service/webjars/**
            - Path=/manager-service/swagger-resources/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/manager-service/(?<segment>.*), /${segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    urls:
      - name: 회원 서비스
        url: /user-service/v3/api-docs
      - name: 관리자 서비스
        url: /manager-service/v3/api-docs
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
